cursor:
  #  # Cursor style
  #  #
  #  # Values for 'style':
  #  #   - â–‡ Block
  #  #   - _ Underline
  #  #   - | Beam
  #  style: Block

  #  # If this is `true`, the cursor will be rendered as a hollow box when the
  #  # window is not focused.
  unfocused_hollow: true
