mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  # URL launcher
  # url:
  # This program is executed when clicking on a text which is recognized as a
  # URL.
  # The URL is always added to the command as the last parameter.
  #
  # When set to `None`, URL launching will be disabled completely.
  #
  # Default:
  #   - (macOS) open
  #   - (Linux) xdg-open
  #   - (Windows) explorer
  # launcher:
  #   program: xdg-open
  #   args: []
  # These are the modifiers that need to be held down for opening URLs when
  # clicking on them. The available modifiers are documented in the key binding
  # section.
  # modifiers: Control|Shift
# selection:
#   semantic_escape_chars: ",â”‚`|:\"' ()[]{}<>"

#   # When set to `true`, selected text will be copied to the primary clipboard.
#   save_to_clipboard: false

# Mouse bindings
#
# Available fields:
# - mouse
# - action
# - mods (optional)
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
# mouse_bindings:
#   - {mouse: Middle, action: PasteSelection}
