[[entries]]
name = "Kagi"
url = "https://kagi.com/search?q=%TERM%"
default = true

[[entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"

[[entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"
