[metadata]
name = "dev-dirs"
description = "A channel to select from directories in ~/dev"
requirements = ["fd"]

[source]
command = ["fd -t d . ~/dev", "fd -t d --hidden . ~/dev"]

[preview]
command = "ls -la --color=always '{}'"

[keybindings]
shortcut = "f2"
