[tools]

"aqua:ahmetb/kubectx/kubens" = "latest" # switch between k8s namespaces
"cargo:ast-grep" = "latest"             # like grep but on code structure!
"cargo:erdtree" = "latest"              # file system tree visualizer with icons and git support
"cargo:eza" = "latest"                  # ls replacement with icons and git support + more
"cargo:fastmod" = "latest"              # fast regex code modifications
"cargo:gping" = "latest"                # graph ping
"cargo:htmlq" = "latest"                # Like jq, but for HTML
"cargo:kdash" = "latest"                # kubernetes dashboard
"cargo:lolcrab" = "latest"              # like lolcat but in rust and with noise
"cargo:rnr" = "latest"                  # A command-line tool to batch rename files and directories
"cargo:sd" = "latest"                   # a modern alternative for sed with sensible defaults
"cargo:wireman" = "latest"              # GRPC TUI client
"gem:tmuxinator" = "latest"             # tmux session manager
"npm:@commitlint/cli" = "latest"        # linter for checking that commits are following conventional commits
"npm:neovim" = "latest"                 # support for javascript plugins in neovim
"npm:npkill" = "latest"                 # easily find and delete heavy node modules
"npm:prettier" = "latest"               # code formatter (js, ts, json, yaml and more)
"npm:tldr" = "latest"                   # useful usage instructions for CLI apps
"npm:trash-cli" = "latest"              # rm -> system trash (cross platform)
"pipx:codespell" = "latest"             # check for spelling mistakes in code.
"pipx:howdoi" = "latest"                # ask for coding help directly from the terminal
"pipx:httpie" = "latest"                # modern, user-friendly CLI HTTP client
"pipx:neovim-remote" = "latest"         # allow controlling neovim remotely
"pipx:posting" = "latest"               # like postman but a TUI
"pipx:yq" = "latest"                    # like jq but for yaml files
"ubi:dlvhdr/diffnav" = "latest"         # A git diff pager based on delta but with a file tree, Ã  la GitHub.
"ubi:joshmedeski/sesh" = "latest"       # tmux session manager
"ubi:mr-karan/doggo" = "latest"         # DNS client (like dig but better)
"ubi:sibprogrammer/xq" = "latest"       # XML and HTML beautifier and content extractor
bat = "latest"                          # modern `cat` with syntax highlighting
choose = "latest"                       # A human-friendly and fast alternative to cut and (sometimes) awk
delta = "latest"                        # nicer git diffs
deno = "2"                              # Deno programming language
dust = "latest"                         # A more intuitive version of du in rust
elixir = "1.18.1-otp-27"                # Elixir programming language
erlang = "27"                           # Erlang programming language
fd = "latest"                           # modern `find`
fx = "latest"                           # like jq, but allows interactive exploration and copying paths
fzf = "latest"                          # fuzzy finder
github-cli = "latest"                   # GitHub CLI
go = "1"                                # Go programming language
gum = "latest"                          # CLI / scripting UI tools
helm = "latest"                         # install k8s packages
hyperfine = "latest"                    # benchmarking tool
jless = "latest"                        # json explorer
jq = "latest"                           # pretty print and query json
kubectl = "latest"                      # k8s cli
kubectx = "latest"                      # switch between k8s clusters and namespaces quickly
lazydocker = "latest"                   # docker TUI
lazygit = "latest"                      # Git TUI
lua = "5"                               # Lua programming language
lua-language-server = "latest"          # Lua Language Server
neovim = "latest"                       # the best text editor/IDE
opentofu = "latest"                     # terraform drop-in alternative, with more permissive license
python = "3.13.2"                         # Python programming language
rebar = "3.24.0"                        # build tool for Erlang (equivalent to mix in Elixir)
ripgrep = "latest"                      # modern `grep`
ruby = "3"                              # Ruby programming language
rust = "1"                              # Rust programming language
starship = "latest"                     # command prompt styling
stylua = "latest"                       # formatter for lua
talosctl = "latest"                     # TalOS K8s OS controller
task = "latest"                         # run tasks (modern make alternative)
terraform = "latest"                    # infrastructure as code
uv = "latest"                           # install python packages
vivid = "latest"                        # generate color schemes for different tools
zoxide = "latest"                       # a modern version of autojump

[tools.node]
version = "22"
postinstall = 'corepack enable && corepack enable pnpm'

[settings]
# needed to enable ruby gems install
experimental = true
