# '##::::'##:'####::'######::'########:
#  ###::'###:. ##::'##... ##: ##.....::
#  ####'####:: ##:: ##:::..:: ##:::::::
#  ## ### ##:: ##::. ######:: ######:::
#  ##. #: ##:: ##:::..... ##: ##...::::
#  ##:.:: ##:: ##::'##::: ##: ##:::::::
#  ##:::: ##:'####:. ######:: ########:
# ..:::::..::....:::......:::........::

# NOTE: cargo backends are slower because they compile from source. I usually
# prefer not to use those, but in some cases there is no ARM64 binary available
# via Aqua / Github - so we have to use cargo, in other cases, there are no
# pre-compiled binaries at all - in such cases we should check periodically if
# binaries were published or contribute a fix to pre-compile binaries for arm64.
#
# Tools with no ARM bins:
# - vivid
# - du-dust

# For the same reason - sometimes github backend is selected when aqua is
# available, if the aqua backend gets the architecture wrong:
# - hyperfine

[tools]

"aqua:ahmetb/kubectx/kubens" = "latest"                                                    # switch between k8s namespaces
"cargo:du-dust" = "latest"                                                                 # A more intuitive version of du in rust
"cargo:erdtree" = "latest"                                                                 # file system tree visualizer with icons and git support
"cargo:fastmod" = "latest"                                                                 # fast regex code modifications
"cargo:htmlq" = "latest"                                                                   # Like jq, but for HTML
"cargo:vivid" = "latest"                                                                   # generate color schemes for different tools
"gem:tmuxinator" = "latest"                                                                # tmux session manager
"github:JohannesKaufmann/html-to-markdown" = { version = "latest", exe = "html2markdown" } # convert HTML to Markdown
"github:ast-grep/ast-grep" = "latest"                                                      # a cli tool for searching and rewriting code using AST
"github:babs/multiping" = "latest"
"github:chmln/sd" = "latest"                                                               # a modern alternative for sed with sensible defaults
"github:dkarter/lnr" = "latest"                                                            # linear cli
"github:dlvhdr/diffnav" = "latest"                                                         # A git diff pager based on delta but with a file tree, Ã  la GitHub.
"github:ip7z/7zip" = { version = "latest", exe = "7zz" }                                   # 7zip cli
"github:ismaelgv/rnr" = "latest"                                                           # batch rename files and directories
"github:joshmedeski/sesh" = "latest"                                                       # tmux session manager
"github:kdash-rs/kdash" = "latest"                                                         # kubernetes dashboard in the terminal
"github:mazznoer/lolcrab" = "latest"                                                       # like lolcat, but written in Rust and with more features
"github:mr-karan/doggo" = "latest"                                                         # DNS client (like dig but better)
"github:nushell/nushell" = { version = "latest", exe = "nu" }                              # modern shell and scripting language
"github:orf/gping" = "latest"                                                              # graph ping
"github:preiter93/wireman" = "latest"                                                      # GRPC CLI
"github:sharkdp/hyperfine" = "latest"                                                      # benchmarking tool
"github:sibprogrammer/xq" = "latest"                                                       # XML and HTML beautifier and content extractor
"github:tidewave-ai/mcp_proxy_rust" = { version = "latest", exe = "mcp-proxy" }            # Elixir MCP proxy
"npm:@anthropic-ai/claude-code" = "latest"                                                 # AI agent
"npm:@commitlint/cli" = "latest"                                                           # linter for checking that commits are following conventional commits
"npm:neovim" = "latest"                                                                    # support for javascript plugins in neovim
"npm:npkill" = "latest"                                                                    # easily find and delete heavy node modules
"npm:opencode-ai" = "latest"
"npm:prettier" = "latest"                                                                  # code formatter (js, ts, json, yaml and more)
"npm:tldr" = "latest"                                                                      # useful usage instructions for CLI apps
"npm:trash-cli" = "latest"                                                                 # rm -> system trash (cross platform)
"pipx:httpie" = "latest"                                                                   # modern, user-friendly CLI HTTP client
"pipx:neovim-remote" = "latest"                                                            # allow controlling neovim remotely
"pipx:posting" = "latest"                                                                  # like postman but a TUI
"pipx:yq" = "latest"                                                                       # like jq but for yaml files
argocd = "latest"
bat = "latest"                                                                             # modern `cat` with syntax highlighting
bun = "latest"                                                                             # faster JS runtime
choose = "latest"                                                                          # A human-friendly and fast alternative to cut and (sometimes) awk
delta = "latest"                                                                           # nicer git diffs
deno = "2"                                                                                 # Deno programming language
direnv = "latest"                                                                          # load env vars on cd
dive = "latest"                                                                            # A tool for exploring each layer in a docker image
elixir = "1.18.2-otp-27"                                                                   # Elixir programming language
erlang = "27"                                                                              # Erlang programming language
fd = "latest"                                                                              # modern `find`
fx = "latest"                                                                              # like jq, but allows interactive exploration and copying paths
fzf = "latest"                                                                             # fuzzy finder
github-cli = "latest"                                                                      # GitHub CLI
gitleaks = "latest"                                                                        # git leaks is a tool for detecting and preventing hardcoded secrets like passwords, API keys, and tokens in git repositories
glow = "latest"                                                                            # Render markdown on the CLI
go = "1"                                                                                   # Go programming language
gum = "latest"                                                                             # CLI / scripting UI tools
helm = "latest"                                                                            # install k8s packages
jless = "latest"                                                                           # json explorer
jq = "latest"                                                                              # pretty print and query json
kubectl = "latest"                                                                         # k8s cli
kubectx = "latest"                                                                         # switch between k8s clusters and namespaces quickly
lazydocker = "latest"                                                                      # docker TUI
lazygit = "latest"                                                                         # Git TUI
lsd = "latest"                                                                             # ls with icons and colors, like `exa` but with more features
lua-language-server = "latest"                                                             # Lua Language Server
marp-cli = "latest"                                                                        # markdown presentation tool
neovim = "latest"                                                                          # the best text editor/IDE
node = "22"                                                                                # Node.js programming language
opentofu = "latest"                                                                        # terraform drop-in alternative, with more permissive license
python = "3.12"                                                                            # Python programming language
rebar = "latest"                                                                           # build tool for Erlang (equivalent to mix in Elixir)
resvg = "latest"                                                                           # svg rendering library and CLI tool (used by yazi)
ripgrep = "latest"                                                                         # modern `grep`
ruby = "3"                                                                                 # Ruby programming language
rust = "1"                                                                                 # Rust programming language
slsa-verifier = "latest"                                                                   # security: tool for verifying SLSA provenance that was generated by CI/CD builders
starship = "latest"                                                                        # command prompt styling
stylua = "latest"                                                                          # formatter for lua
task = "latest"                                                                            # run tasks (modern make alternative)
television = "latest"                                                                      # fancy fuzzy finder with shell integration and "channels"
terraform = "latest"                                                                       # infrastructure as code
typos = "latest"                                                                           # type checker alternative to codespell
usage = "latest"                                                                           # generates completion scripts for various tools (including mise)
uv = "latest"                                                                              # install python packages
yazi = "latest"                                                                            # terminal file manager
zoxide = "latest"                                                                          # a modern version of autojump


# allow specific asdf plugins when there's no other option
# docs: https://mise.jdx.dev/dev-tools/aliases.html
# list of asdf plugins that would normally be supported https://mise.jdx.dev/registry.html#tools
[tool_alias]
rebar = 'asdf:mise-plugins/mise-rebar'
redis = 'asdf:mise-plugins/mise-redis'

[settings]
# needed to enable ruby gems install
experimental = true
disable_backends = ["asdf"]
# use bun instead of npm when using npm:<package>
npm.bun = true
